# Use official Python image
FROM python:3.13-slim

# Metadata
LABEL maintainer="Gopi Krishna Maganti <gopi.maganti1998@gmail.com>"
LABEL description="Dockerfile for Backend of PMT (Project Management Tool) using Django and PostgreSQL"

# Set working directory
WORKDIR /app

# Copy only requirements first for caching
COPY requirements /app/requirements

# Install dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements/base.txt

# OPTIONAL: install test dependencies (uncomment for dev)
RUN pip install -r requirements/test.txt

# Copy Django project
COPY . /app/

# Change permissions for entrypoint script
RUN chmod +x /app/entrypoint.sh

# Entrypoint
ENTRYPOINT ["sh", "/app/entrypoint.sh"]
