# Generated by Django 5.2.2 on 2025-06-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="assignee",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="project",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="reporter",
        ),
        migrations.RemoveField(
            model_name="issueauditlog",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="issueauditlog",
            name="action_by",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="project",
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Issue",
        ),
        migrations.DeleteModel(
            name="IssueAuditLog",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectMember",
        ),
    ]
